import { Hero } from "@/components/Hero";
import { Feed } from "@/components/layouts/Feed";
import clsx from "clsx";
import { allBlogs } from "contentlayer/generated";
import type { Metadata } from "next";
import { MdAlternateEmail } from "react-icons/md";
import { TbBrandGithub, TbBrandLinkedin } from "react-icons/tb";
import { lexendDeca } from "../fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Posts() {
  return (
    <main className="flex min-h-screen flex-col items-center">
      <div className="px-container relative mx-auto m-8 max-w-container">
        <Hero
          title={HeroTitle}
          description="Transforming distributed system challenges into production-ready features and unlocking seamless scalability and robust, resilient architectures."
          actions={HeroActions}
        />
      </div>
      <div className="z-10 max-w-2xl w-full items-center justify-between text-sm lg:flex">
        <div className="flex flex-col w-full max-w-3xl my-16">
          <Feed>
            {allBlogs.map(({ summary, publishedAt, slug, title }) => (
              <Feed.Item
                key={slug}
                link={`/blogs/${slug}`}
                title={title}
                summary={summary}
                publishedAt={publishedAt}
              />
            ))}
          </Feed>
        </div>
      </div>
    </main>
  );
}

const HeroTitle = (
  <div className={clsx(lexendDeca.className)}>
    <span className="block text-violet-400">Distributed,</span>
    <span className="block">product building.</span>
  </div>
);

const HeroActions = (
  <div className="mt-6 flex-col items-center justify-center text-center">
    <div className="mt-10 flex justify-center gap-8 lg:justify-start">
      <a
        className="rounded-lg text-slate-900 font-semibold transition flex items-center gap-3 text-[0.8125rem] leading-6 py-1 px-1.5 hover:bg-slate-900/[0.03] -my-1 -mx-1.5 dark:text-gray-400"
        href="https://github.com/pyadav"
      >
        <TbBrandGithub
          aria-hidden
          className="h-5 w-5 transition-transform group-hover:translate-x-0.5"
        />
        Github
      </a>
      <a
        className="rounded-lg text-slate-900 font-semibold transition flex items-center gap-3 text-[0.8125rem] leading-6 py-1 px-1.5 hover:bg-slate-900/[0.03] -my-1 -mx-1.5 dark:text-gray-400"
        href="https://www.linkedin.com/in/iamya6av"
      >
        <TbBrandLinkedin style={{ marginTop: "-4" }} />
        Linkedin
      </a>
      <a
        className="rounded-lg text-slate-900 font-semibold transition flex items-center gap-3 text-[0.8125rem] leading-6 py-1 px-1.5 hover:bg-slate-900/[0.03] -my-1 -mx-1.5 dark:text-gray-400"
        href="mailto:pyadav9678@gmail.com"
      >
        <MdAlternateEmail style={{ marginTop: "-4" }} />
        Email me
      </a>
    </div>
  </div>
);
