import GoogleAnalytics from "@/components/GA";
import Layout from "@/components/layouts/Main";
import { inter, lexendDeca, wotfard } from "app/fonts";
import clsx from "clsx";
import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={clsx(inter.variable, lexendDeca.variable, wotfard.className)}
      >
        <ThemeProvider>
          <Layout>
            {process.env.NEXT_PUBLIC_GA_TRACKING_ID &&
            process.env.NODE_ENV === "production" ? (
              <GoogleAnalytics ga_id={process.env.NEXT_PUBLIC_GA_TRACKING_ID} />
            ) : null}
            {children}
          </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
